### ISSUE TITLE
Api key has been left in development code.

### ISSUE THREAD

**Issue by gwuah** [jajoosam/chhota#1]
var googleApiLoaded = function() {
gapi.client. setApiKey( "" ) 

:(

**Comment by leovarmak** [comment]
+1.
@jajoosam Get this fixed ASAP

**Comment by jajoosam** [comment]
Fixed :smile:

**Comment by leovarmak** [comment]
AH Shit. I was just second away from sending a pull request

**Comment by gwuah** [comment]
I should have sent in a pull request. 😢😢
I just missed my chance of contributing to a great initiative. Damn! 😢😢

**Comment by jajoosam** [comment]
You already contributed by spotting the issue :)

**Comment by leovarmak** [comment]
Haha. 
@jajoosam Soo much ❤ for your projects.
@gwuah Have a look at his other repos. He can surely use your help.

**Comment by gwuah** [comment]
@leovamak I sure will!
